ccclimate/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^options/', include('options.urls')),
    url(r'^admin/', admin.site.urls),
]

options/urls.py
from django.conf.urls import url

from . import views
app_name = 'options'

urlpatterns = [

    # ex: /pru/
     url(r'^$', views.index, name='index'),
     url(r'^mapa', views.mapa, name='mapa'),

    # ex: /localizaciones/
   #  url(r'^$', views.index, name='index'),
    # ex: /localizaciones/index
  #   url(r'^index2/$', views.index2, name='index2'),
    # ex: /localizaciones/5/
  #   url(r'^(?P<localizacion_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /localizaciones/5/results/
  #   url(r'^(?P<localizacion_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /datos/localizaciones/5/
 #    url(r'^datos/(?P<localizacion_id>[0-9]+)/$', views.datos, name='datos'),
    # ex: /datos/localizaciones/5/resultados/
 #    url(r'^datos/(?P<localizacion_id>[0-9]+)/resultados/$', views.resultados, name='resultados'),
    # ex: /mapa/localizaciones/5/resultados/
   ## url(r'^mapa/$', views.mapa, name='mapa'),
  #   url(r'^pru2/$', views.pru2, name='pru2'),
 #    url(r'^mapa(?P<localizacion_id>[0-9]+)/$', views.mapa, name='mapa'),

]

options/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

''' 
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
'''
class Option(models.Model):
    option_type = models.CharField(max_length=200)
    option_code = models.CharField(max_length=200)
    option_text = models.CharField(max_length=200)
    def __str__(self):
        return self.option_type + " "+ self.option_code

@python_2_unicode_compatible  # only if you need to support Python 2
class Localizacion(models.Model):
    lugar_id = models.CharField(max_length=200)
    lugar_ds = models.CharField(max_length=200)
    def __str__(self):
        return self.lugar_ds 
@python_2_unicode_compatible  # only if you need to support Python 2
class Coordenadas(models.Model):
    local_ref = models.ForeignKey(Localizacion, on_delete=models.CASCADE)
    latitud = models.DecimalField(max_digits=15, decimal_places=10)
    longitud = models.DecimalField(max_digits=15, decimal_places=10) 
    descripcion = models.CharField(max_length=200, null=True) 
    def return_coordenadas(self):
     return self.latitud + self.longitud
    def __str__(self):
        return self.descripcion

options/views.py
from django.http import HttpResponse
from .models import Localizacion
from .models import Coordenadas
from django.template import loader
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render_to_response

from .models import Option
from .models import Localizacion
from .models import Coordenadas
from . import readExcel
from . import DataparametersClasss
from . import ECMWF_dataRecover01

import math
import json
import urllib.request, urllib.parse, urllib.error
import re

class GoogleCoords():
    def __init__(self, lat, lon, ds):
        self.lat = lat
        self.lon = lon
        self.ds = ds

    def __str__(self):
        return self.ds
		
##Función BuscarCoordenadas -------------------
def BuscarCoordenadas(direccion):
    serviceurl = 'http://maps.googleapis.com/maps/api/geocode/json?'
    # serviceurl = 'http://python-data.dr-chuck.net/geojson?'
    url = serviceurl + urllib.parse.urlencode({'sensor':'false', 'address': direccion})
    print ('Retrieving', url)
    uh = urllib.request.urlopen(url) 
    data = (uh.read().decode(uh.info().get_param('charset') or 'utf-8'))
    print ('Retrieved',len(data),'characters from GoogleMaps')
    try: js = json.loads(str(data))
    except: js = None
    print("js: ",js)
    if ('status' not in js) or (js['status'] != 'OK'):
        print ('==== Failure To Retrieve ====')
        print (data)
    print (json.dumps(js, indent=4))
    lat = js["results"][0]["geometry"]["location"]["lat"]
    lng = js["results"][0]["geometry"]["location"]["lng"]
    formatted_address = js["results"][0]["formatted_address"]
    print ('lat',lat,'lng',lng)
    location = js['results'][0]['formatted_address']
    print (location)
    place_id = js['results'][0]['place_id']
    print (place_id)
    return(GoogleCoords(lat,lng,formatted_address))
# Create your views here.
def index(request):
    location=0
    if request.method == 'POST':
       existsLocalization = Localizacion.objects.filter(lugar_id = request.POST['lugar'] )
       if existsLocalization.count()==0:
         location= Localizacion.objects.create(lugar_id=request.POST['lugar']  , lugar_ds=request.POST['lugar']  )
         localizacion_id=location.id
         if location!=0:
            coordenadas = BuscarCoordenadas(location.lugar_ds)
            try:
                  coordenadasl = Coordenadas.objects.filter(local_ref = location.id)
                  coordenadasl.delete()
            except:
                  pass
            location.coordenadas_set.create(latitud=coordenadas.lat, longitud=coordenadas.lon, descripcion=coordenadas.ds)
            opcion= Option.objects.create(option_code=location.id ,option_type="lugares", option_text=coordenadas.ds )

    opcionesTemperatura = Option.objects.filter(option_type = "temperaturas")
    opcionesEcoRiverFlow = Option.objects.filter(option_type = "ecological river flow")
    opcionesMaximumFlow = Option.objects.filter(option_type = "Maximun flow")
    opcionesReservoirCapacity = Option.objects.filter(option_type = "Reservoir capacity")
    opcionesLugares = Option.objects.filter(option_type = "lugares")
    opcionesNetFalling = Option.objects.filter(option_type = "net falling height or head")
    opcionesNumberOfTurbines = Option.objects.filter(option_type = "Number of turbines")
    opcionesTypeOfTurbine = Option.objects.filter(option_type = "Type of turbines")
    anios = Option.objects.filter(option_type = "year")
    context = {
	   'opcionesTemperatura': opcionesTemperatura,
	   'opcionesEcoRiverFlow': opcionesEcoRiverFlow,
	   'opcionesMaximumFlow': opcionesMaximumFlow,
	   'opcionesReservoirCapacity': opcionesReservoirCapacity,
	   'opcionesNetFalling': opcionesNetFalling,
	   'opcionesNumberOfTurbines': opcionesNumberOfTurbines,
	   'opcionesTypeOfTurbine': opcionesTypeOfTurbine,
	   'opcionesLugares': opcionesLugares,
	   'anios': anios,
    }
    return render(request, 'options/index.html', context)


def mapa(request):
    type=""
    if '_caudal' in request.POST:
     type="_caudal"
    if '_energia' in request.POST:
     type="_energia"
    if '_periodos' in request.POST:
     type="_periodos"
    if '_forecast' in request.POST:
     type="_forecast"
    if type=="_forecast":
        return(ECMWF_dataRecover01.calculaCaudal(request))

    elif 'localizacion_id' in request.POST:
        localizacion_id=request.POST['localizacion_id']
        opcionesEcoRiverFlow=request.POST['opcionesEcoRiverFlow']
        opcionesMaximumFlow=request.POST['opcionesMaximumFlow']
        opcionesReservoirCapacity=request.POST['opcionesReservoirCapacity']
        opcionesNetFalling=request.POST['opcionesNetFalling']
        opcionesNumberOfTurbines=request.POST['opcionesNumberOfTurbines']
        opcionesTypeOfTurbine=request.POST['opcionesTypeOfTurbine']
        location = get_object_or_404(Localizacion, pk=localizacion_id)
        try:
            coordenadas = Coordenadas.objects.filter(local_ref = location.id)
            if type=="_caudal":
                return(readExcel.calculaCaudal(request, coordenadas[0].latitud, coordenadas[0].longitud,coordenadas[0].descripcion))
            if type=="_energia":
                dataparameters =DataparametersClasss.DataparametersClasss ()

                dataparameters.opcionesEcoRiverFlow=opcionesEcoRiverFlow
                dataparameters.opcionesMaximumFlow=opcionesMaximumFlow
                dataparameters.opcionesReservoirCapacity=opcionesReservoirCapacity
                dataparameters.opcionesNetFalling=opcionesNetFalling
                dataparameters.opcionesNumberOfTurbines=opcionesNumberOfTurbines
                dataparameters.opcionesTypeOfTurbine=opcionesTypeOfTurbine
                return(readExcel.calculaEnergia(request, coordenadas[0].latitud, coordenadas[0].longitud,coordenadas[0].descripcion,dataparameters))
            if type=="_periodos":
                dataparameters =DataparametersClasss.DataparametersClasss ()

                dataparameters.opcionesEcoRiverFlow=opcionesEcoRiverFlow
                dataparameters.opcionesMaximumFlow=opcionesMaximumFlow
                dataparameters.opcionesReservoirCapacity=opcionesReservoirCapacity
                dataparameters.opcionesNetFalling=opcionesNetFalling
                dataparameters.opcionesNumberOfTurbines=opcionesNumberOfTurbines
                dataparameters.opcionesTypeOfTurbine=opcionesTypeOfTurbine
                return(readExcel.calculaPeriodo(request, coordenadas[0].latitud, coordenadas[0].longitud,coordenadas[0].descripcion,dataparameters))
        except:
            print("****errir**")

options/templates/options/forecastflow.html
<!doctype html>
<!-- django 'mathfilters' is not a registered tag library. -->
{% load mathfilters %}
{% load static %}
{% if valores %}
<script> valores={{valores}}</script>
<script> anios={{anios}}</script>
{% endif %}
 
<html lang="en">
<script  src="{% static 'js/queue.v1.min.js' %}"  ></script>
  
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
<script  src="{% static 'js/topojson.js' %}"  ></script>
<script  src="{% static 'js/jquery-3.0.0.min.js' %}" ></script>


<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>River flow (Catchments)</title>

</head>
<body>

<section class='container'>
          <hgroup>
            <h1>River flow (Catchments)  </h1>
          </hgroup>
<form method="post">
<!--
<input name="prueba" id="prueba" value="value to sent"/>
<input type="submit" value="boton aceptar" />
-->
     <div class="row">
          <section class='col-xs-12 col-sm-12 col-md-12'>
				
<div id="chart"></div>
<section>
<script>
data0 = []
columns=[]
columns2=[]

modelos=[]
{%for  modelo in namemodelos%}
modelos.push("{{modelo}}")
{%endfor%} 

data0.push('x')
{%for elem in anios%}
	data0.push("{{elem}}T00:00:00.000Z")
{%endfor%} 
columns.push(data0)
data=[]
    data.push("Flow Forecast")

{%for  elem in valores%}
    data.push({{elem}})
{%endfor%} 
columns.push(data{{forloop.counter}})

 var mydata={}
 mydata.x='x';
 mydata.xFormat='%Y-%m-%dT%H:%M:%S.%LZ',
 mydata.columns=columns;
 var maxis={}
 var xaxis={}
 xaxis.type= 'timeseries';
 var tick={}
 tick.format= "%Y-%m-%d";
 tick.rotate= 75;
 tick.count=30;
 tick.culling=false;
 tick.fit=false;
 tick.multiline=false;
 xaxis.tick=tick
 maxis.x=xaxis;

  var chart = c3.generate({
    bindto: '#chart',
    data: mydata,
	axis:maxis
})

Array.prototype.sum = Array.prototype.sum || function() {
  return this.reduce(function(sum, a) { return sum + Number(a) }, 0);
}

Array.prototype.average = Array.prototype.average || function() {
  return this.sum() / (this.length || 1);
}


var newArray = $.map(mydata,function(elem, pos){
  average=[]
  average.push("Average")
  for (i=1; i<columns[0].length;i++){
    valores=[]
    for (j=1;j<columns.length;j++){
        valor=columns[j][i]
        valores.push(valor)
    }
    average.push(valores.average() )
  }  
  return average;
});


</script>
</section>

          </section>

        </div>

        
        <footer>
          <div class="logo"><a href="climatecoders"></a></div>
        </footer>

</section>
</body>
</html>

options/templates/options/index.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta htttp-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Toma de datos</title>

</head>
<body>
<form action="" method="post">
{% csrf_token %}

  <fieldset class="module aligned ">
    
    
    

        <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Localización a Añadir: </label>
                        
                            <input class="vTextField" id="lugar" maxlength="200" name="lugar" type="text" value="" required />
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>
<div class="submit-row">
<input type="submit" value="Consultar Latitud y Longitud" class="default" name="_consulta" />

</div>



</form>

<form name="inputData" action="{% url 'options:mapa' %}" method="Post">
{% csrf_token %}

  <fieldset class="module aligned ">
    
 
        <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Lugar</label>
                        
                            <select class="vTextField" id="id_lugar_sel" maxlength="200" name="id_lugar_sel"  type="text"  required onchange="document.getElementById('localizacion_id').value=+this.value">
							{% for opcion in opcionesLugares.all %}
								<option value="{{ opcion.option_code }}">{{ opcion.option_text }}</option>
							{% endfor %}
							</select> 
                        
						<input class="vTextField" id="localizacion_id" maxlength="200" name="localizacion_id"  type="TEXT"  VALUE="32" >

                    
                </div>
            
        </div>
           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Ecological River Flow</label>
                        
                            <input class="vTextField" id="opcionesEcoRiverFlow" maxlength="200" name="opcionesEcoRiverFlow" type="text"  required>
						<span>	{% for opcion in opcionesEcoRiverFlow.all %}
								{{ opcion.option_text }}
							{% endfor %}</span>
							</select>
                        
                    
                    
                </div>
            
        </div> 
		           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Maximum Flow</label>
                        
                            <input class="vTextField" id="opcionesMaximumFlow" maxlength="200" name="opcionesMaximumFlow" type="text"  required>
						<span>	{% for opcion in opcionesMaximumFlow.all %}
								{{ opcion.option_text }}
							{% endfor %}</span>
							</select>
                        
                    
                    
                </div>
            
        </div> 
				           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Reservoir Capacity</label>
                        
                            <input class="vTextField" id="opcionesReservoirCapacity" maxlength="200" name="opcionesReservoirCapacity" type="text"  required>
						<span>	{% for opcion in opcionesReservoirCapacity.all %}
								{{ opcion.option_text }}
							{% endfor %}</span>
							</select>
                        
                    
                    
                </div>
            
        </div> 
		
				           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Net Head</label>
                        
                            <input class="vTextField" id="opcionesNetFalling" maxlength="200" name="opcionesNetFalling" type="text"  required>
						<span>	{% for opcion in opcionesNetFalling.all %}
								{{ opcion.option_text }}
							{% endfor %}</span>
							</select>
                        
                    
                    
                </div>
            
        </div> 
				           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">Number Of Turbines</label>
                        
                            <input class="vTextField" id="opcionesNumberOfTurbines" maxlength="200" name="opcionesNumberOfTurbines" type="text"  required>
						<span>	{% for opcion in opcionesNumberOfTurbines.all %}
								{{ opcion.option_text }}
							{% endfor %}</span>
							</select>
                        
                    
                    
                </div>
            
        </div> 

           <div class="form-row field-option_type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_option_type">TypeOfTurbine</label>
                        
                            <select class="vTextField" id="opcionesTypeOfTurbine" maxlength="200" name="opcionesTypeOfTurbine" type="text"  required>
							{% for opcion in opcionesTypeOfTurbine.all %}
								<option>{{ opcion.option_code }}</option>
							{% endfor %}
							</select>
                        
                    
                    
                </div>
            
        </div> 
		
		<div class="submit-row">
<input type="submit"  value="Consulta Caudal" class="default" id="_caudal" name="_caudal" />
<input type="submit"  value="Consulta Energia" class="default" id="_energia" name="_energia" />
<input type="submit"  value="Consulta Periodos" class="default" id="_periodos" name="_periodos" />

</div>
</fieldset>
<!--
<div class="submit-row">
<input type="button" onclick="document.getElementById('grafica').src='{% url 'options:mapa' %}?localizacion_id='+document.getElementById('id_lugar_sel').value" value="Consulta Caudal" class="default" name="_caudal" />
-->
</div>



</form>
<form name="inputData2" action="{% url 'options:mapa' %}" method="Post">
{% csrf_token %}

<BR/>
<input type="submit"  value="Flow Forecast" class="default" id="_forecast" name="_forecast" />
</form>

<!--
<iframe style="width:1200px;height:500px" id="grafica" src="">
</iframe>
-->
</body>
</html>

options/templates/options/mapa.html
<!doctype html>
<!-- django 'mathfilters' is not a registered tag library. -->
{% load mathfilters %}
{% load static %}
{% if valores %}
<script> valores={{valores}}</script>
<script> namemodelos={{namemodelos}}</script>

<script> anios={{anios}}</script>
<script> lugar ="{{lugar}}"</script>
<script> dataparametersSt ="{{dataparametersSt}}"</script>
{% endif %}
 
<html lang="en">
<script  src="{% static 'js/queue.v1.min.js' %}"  ></script>
  
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
<script  src="{% static 'js/topojson.js' %}"  ></script>
<script  src="{% static 'js/jquery-3.0.0.min.js' %}" ></script>


<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>River flow (Catchments)</title>

</head>
<body>

<section class='container'>
          <hgroup>
            <h1>River flow (Catchments) - {{lugar}} - {{dataparametersSt}} </h1>
          </hgroup>
<form method="post">
<!--
<input name="prueba" id="prueba" value="value to sent"/>
<input type="submit" value="boton aceptar" />
-->
     <div class="row">
          <section class='col-xs-12 col-sm-12 col-md-12'>
				
<div id="chart"></div>
<section>
<script>
data0 = []
columns=[]
columns2=[]

modelos=[]
{%for  modelo in namemodelos%}
modelos.push("{{modelo}}")
{%endfor%} 

data0.push('x')
{%for value in anios%}
{%for elem in value %}
	data0.push("{{elem}}T00:00:00.000Z")
{%endfor%}
{%endfor%} 
columns.push(data0)

{%for  value in valores%}
data{{forloop.counter}}=[]
data{{forloop.counter}}.push(modelos['{{forloop.counter}}'-1])
    {%for elem in value %}
        data{{forloop.parentloop.counter}}.push({{elem}})
    {%endfor%}
    columns.push(data{{forloop.counter}})
{%endfor%} 

 var mydata={}
 mydata.x='x';
 mydata.xFormat='%Y-%m-%dT%H:%M:%S.%LZ',
 mydata.columns=columns;
 var maxis={}
 var xaxis={}
 xaxis.type= 'timeseries';
 var tick={}
 tick.format= "%Y";
 tick.fit=false;
 xaxis.tick=tick
 maxis.x=xaxis;

  var chart = c3.generate({
    bindto: '#chart',
    data: mydata,
	axis:maxis
})

Array.prototype.sum = Array.prototype.sum || function() {
  return this.reduce(function(sum, a) { return sum + Number(a) }, 0);
}

Array.prototype.average = Array.prototype.average || function() {
  return this.sum() / (this.length || 1);
}


var newArray = $.map(mydata,function(elem, pos){
  average=[]
  average.push("Average")
  for (i=1; i<columns[0].length;i++){
    valores=[]
    for (j=1;j<columns.length;j++){
        valor=columns[j][i]
        valores.push(valor)
    }
    average.push(valores.average() )
  }  
  return average;
});


</script>
</section>
<!--
    <section>
    <div id="chartMedia"></div>

<script>

var monthNames = [ "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT","NOV", "DEC" ];

function jarh(x) {
var y = 365;
var y2 = 31;
var remainder = x % y;
var casio = remainder % y2;
year = (x - remainder) / y;
month = (remainder - casio) / y2;

var result ="--- Year ---" + year + "--- Month ---" + month + "--- Day ---" + casio;

return month;
}

 var mydata2={}
 mydata2.x='x';
 columns2.push(newArray)
 mydata2.columns=columns2;
  var chartMedia = c3.generate({
    bindto: '#chartMedia',
    data: mydata2,
    axis : {
        x : {
            type : 'timeseries',
            tick: {
                format: function (x) {return monthNames[jarh(x)];}
              //format: '%Y' // format string is also available for timeseries data
            }
        }
    }


});




</script>
    </section> -->
          </section>

        </div>

        
        <footer>
          <div class="logo"><a href="climatecoders"></a></div>
        </footer>

</section>
</body>
</html>

options/templates/options/mapaResumen.html
<!doctype html>
<!-- django 'mathfilters' is not a registered tag library. -->
{% load mathfilters %}
{% load static %}
{% if valores %}
<script> valores={{valores}}</script>
<script> namemodelos={{namemodelos}}</script>
<script> anios={{anios}}</script>
<script> lugar ="{{lugar}}"</script>
<script> dataparametersSt ="{{dataparametersSt}}"</script>
{% endif %}
 
<html lang="en">
<script  src="{% static 'js/queue.v1.min.js' %}"  ></script>
  
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
<script  src="{% static 'js/topojson.js' %}"  ></script>
<script  src="{% static 'js/jquery-3.0.0.min.js' %}" ></script>


<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>River flow (Catchments)</title>

</head>
<body>

<section class='container'>
          <hgroup>
            <h1>River flow (Catchments) - {{lugar}} - {{dataparametersSt}} </h1>
          </hgroup>
<form method="post">
<!--
<input name="prueba" id="prueba" value="value to sent"/>
<input type="submit" value="boton aceptar" />
-->
     <div class="row">
          <section class='col-xs-12 col-sm-12 col-md-12'>
				
<div id="chart"></div>
<section>
<script>
data0 = []
columns=[]
columns2=[]



modelos=[]
{%for  modelo in namemodelos%}
modelos.push("{{modelo}}")
{%endfor%} 

{%for  value in valores%}
data{{forloop.counter}}=[]
data{{forloop.counter}}.push(modelos['{{forloop.counter}}'-1])
    {%for elem in value %}
        data{{forloop.parentloop.counter}}.push({{elem}})
    {%endfor%}
    columns.push(data{{forloop.counter}})
{%endfor%} 

 var mydata={}
 mydata.columns=columns;
 var maxis={}
 var xaxis={}
 var tick={}
 tick.format= function (x) {  switch(x){case 0:return "historical"; case 1:return("2011-2040");case 2:return "2041-2070"; case 3:return("2071-2100");} }
 tick.fit=false;
 xaxis.tick=tick
 maxis.x=xaxis;

  var chart = c3.generate({
    bindto: '#chart',
    data: mydata,
	axis:maxis
})
Array.prototype.sum = Array.prototype.sum || function() {
  return this.reduce(function(sum, a) { return sum + Number(a) }, 0);
}

Array.prototype.average = Array.prototype.average || function() {
  return this.sum() / (this.length || 1);
}


var newArray = $.map(mydata,function(elem, pos){
  average=[]
  average.push("Average")
  for (i=1; i<columns[0].length;i++){
    valores=[]
    for (j=1;j<columns.length;j++){
        valor=columns[j][i]
        valores.push(valor)
    }
    average.push(valores.average() )
  }  
  return average;
});


</script>
</section>
<!--
    <section>
    <div id="chartMedia"></div>

<script>

var monthNames = [ "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT","NOV", "DEC" ];

function jarh(x) {
var y = 365;
var y2 = 31;
var remainder = x % y;
var casio = remainder % y2;
year = (x - remainder) / y;
month = (remainder - casio) / y2;

var result ="--- Year ---" + year + "--- Month ---" + month + "--- Day ---" + casio;

return month;
}

 var mydata2={}
 mydata2.x='x';
 columns2.push(newArray)
 mydata2.columns=columns2;
  var chartMedia = c3.generate({
    bindto: '#chartMedia',
    data: mydata2,
    axis : {
        x : {
            type : 'timeseries',
            tick: {
                format: function (x) {return monthNames[jarh(x)];}
              //format: '%Y' // format string is also available for timeseries data
            }
        }
    }


});




</script>
    </section> -->
          </section>

        </div>

        
        <footer>
          <div class="logo"><a href="climatecoders"></a></div>
        </footer>

</section>
</body>
</html>